const sampleListings = [
 {
  title: "Elite Book House",
  name: "Elite Book House",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Karol Bagh, Delhi",
  contact: "9876543210",
  alternateContact: "9123456789",
  whatsappNumber: "9876543210",
  email: "elitebookhouse@gmail.com",
  website: "https://elitebookhouse.com",
  googleMapLink: "https://maps.google.com/elitebookhouse",
  facebookPage: "https://facebook.com/elitebookhouse",
  instagramPage: "https://instagram.com/elitebookhouse",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753635319/book1_dzdqln.jpg", filename: "book1_dzdqln" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Peaceful Pages Library",
  name: "Peaceful Pages Library",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Saket, Delhi",
  contact: "9345678901",
  alternateContact: "9567890123",
  whatsappNumber: "9345678901",
  email: "peacefulpages@gmail.com",
  website: "https://peacefulpages.com",
  googleMapLink: "https://maps.google.com/peacefulpages",
  facebookPage: "https://facebook.com/peacefulpages",
  instagramPage: "https://instagram.com/peacefulpages",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753635407/lib3_slu8aj.jpg", filename: "lib3_slu8aj" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Creative Supplies",
  name: "Creative Supplies",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Chandni Chowk, Delhi",
  contact: "9123456780",
  alternateContact: "9876501234",
  whatsappNumber: "9123456780",
  email: "creativesupplies@gmail.com",
  website: "https://creativesupplies.com",
  googleMapLink: "https://maps.google.com/creativesupplies",
  facebookPage: "https://facebook.com/creativesupplies",
  instagramPage: "https://instagram.com/creativesupplies",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753635837/store7_s9xnyb.jpg", filename: "store7_s9xnyb" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Web Zone",
  name: "Web Zone",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Malviya Nagar, Delhi",
  contact: "9876501235",
  alternateContact: "9345678902",
  whatsappNumber: "9876501235",
  email: "webzone@gmail.com",
  website: "https://webzone.com",
  googleMapLink: "https://maps.google.com/webzone",
  facebookPage: "https://facebook.com/webzone",
  instagramPage: "https://instagram.com/webzone",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753636240/cafe2_vos1se.jpg", filename: "cafe2_vos1se" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Excel Coaching",
  name: "Excel Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Mukherjee Nagar, Delhi",
  contact: "9345678903",
  alternateContact: "9123456782",
  whatsappNumber: "9345678903",
  email: "excelcoaching@gmail.com",
  website: "https://excelcoaching.com",
  googleMapLink: "https://maps.google.com/excelcoaching",
  facebookPage: "https://facebook.com/excelcoaching",
  instagramPage: "https://instagram.com/excelcoaching",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753636367/coach1_jqydb6.jpg", filename: "coach1_jqydb6" },
  owner: "6870b24612c47ddfa98a0fa5",
},
// ... Repeat this pattern for remaining 30 listings ...

  {
  title: "Book Nest",
  name: "Book Nest Store",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Janakpuri, Delhi",
  contact: "9876543210",
  alternateContact: "9123456789",
  whatsappNumber: "9876543210",
  email: "bookneststore@gmail.com",
  website: "https://bookneststore.com",
  googleMapLink: "https://maps.google.com/bookneststore",
  facebookPage: "https://facebook.com/bookneststore",
  instagramPage: "https://instagram.com/bookneststore",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753636468/book2_siddzg.jpg", filename: "book2_siddzg" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "The Knowledge Room",
  name: "Knowledge Room Library",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Pitampura, Delhi",
  contact: "9345678901",
  alternateContact: "9567890123",
  whatsappNumber: "9345678901",
  email: "knowledgeroom@gmail.com",
  website: "https://knowledgeroom.com",
  googleMapLink: "https://maps.google.com/knowledgeroom",
  facebookPage: "https://facebook.com/knowledgeroom",
  instagramPage: "https://instagram.com/knowledgeroom",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753636702/lib1_orkaq8.jpg", filename: "lib1_orkaq8" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Note & Write",
  name: "Note & Write Stationers",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Ashok Vihar, Delhi",
  contact: "9123456780",
  alternateContact: "9876501234",
  whatsappNumber: "9123456780",
  email: "notewrite@gmail.com",
  website: "https://notewrite.com",
  googleMapLink: "https://maps.google.com/notewrite",
  facebookPage: "https://facebook.com/notewrite",
  instagramPage: "https://instagram.com/notewrite",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753636819/store2_ras84h.jpg", filename: "store2_ras84h" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Speed Net Cafe",
  name: "Speed Net Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Kalkaji, Delhi",
  contact: "9876501235",
  alternateContact: "9345678902",
  whatsappNumber: "9876501235",
  email: "speednetcafe@gmail.com",
  website: "https://speednetcafe.com",
  googleMapLink: "https://maps.google.com/speednetcafe",
  facebookPage: "https://facebook.com/speednetcafe",
  instagramPage: "https://instagram.com/speednetcafe",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753636908/cafe8_wzu7e6.jpg", filename: "cafe8_wzu7e6" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Prime Success Tutorials",
  name: "Prime Success Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Vaishali, Ghaziabad",
  contact: "9345678903",
  alternateContact: "9123456782",
  whatsappNumber: "9345678903",
  email: "primesuccess@gmail.com",
  website: "https://primesuccess.com",
  googleMapLink: "https://maps.google.com/primesuccess",
  facebookPage: "https://facebook.com/primesuccess",
  instagramPage: "https://instagram.com/primesuccess",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753636964/coach5_rvdqlg.jpg", filename: "coach5_rvdqlg" },
    owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Readers' Stop",
  name: "Readers' Stop Bookstore",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Rohini, Delhi",
  contact: "9876549870",
  alternateContact: "9123487654",
  whatsappNumber: "9876549870",
  email: "readersstop@gmail.com",
  website: "https://readersstop.com",
  googleMapLink: "https://maps.google.com/readersstop",
  facebookPage: "https://facebook.com/readersstop",
  instagramPage: "https://instagram.com/readersstop",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753637013/store4_cqpwow.jpg", filename: "store4_cqpwow" },
   owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Brainwave Library",
  name: "Brainwave Study Library",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "GTB Nagar, Delhi",
  contact: "9345634123",
  alternateContact: "9567845632",
  whatsappNumber: "9345634123",
  email: "brainwavelibrary@gmail.com",
  website: "https://brainwavelibrary.com",
  googleMapLink: "https://maps.google.com/brainwavelibrary",
  facebookPage: "https://facebook.com/brainwavelibrary",
  instagramPage: "https://instagram.com/brainwavelibrary",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753637086/lib4_c24kke.jpg", filename: "llib4_c24kke" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Office Mart",
  name: "Office Mart Stationery",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Tilak Nagar, Delhi",
  contact: "9123487632",
  alternateContact: "9876509876",
  whatsappNumber: "9123487632",
  email: "officemart@gmail.com",
  website: "https://officemart.com",
  googleMapLink: "https://maps.google.com/officemart",
  facebookPage: "https://facebook.com/officemart",
  instagramPage: "https://instagram.com/officemart",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753637302/store5_spizv0.jpg", filename: "store5_spizv0" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Net Connect",
  name: "Net Connect Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Mayur Vihar, Delhi",
  contact: "9876512345",
  alternateContact: "9345678923",
  whatsappNumber: "9876512345",
  email: "netconnect@gmail.com",
  website: "https://netconnect.com",
  googleMapLink: "https://maps.google.com/netconnect",
  facebookPage: "https://facebook.com/netconnect",
  instagramPage: "https://instagram.com/netconnect",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753637449/cafe4_mg1vtx.jpg", filename: "cafe4_mg1vtx" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Vision Tutorials",
  name: "Vision Success Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Shahdara, Delhi",
  contact: "9345671243",
  alternateContact: "9123456787",
  whatsappNumber: "9345671243",
  email: "visionsuccess@gmail.com",
  website: "https://visionsuccess.com",
  googleMapLink: "https://maps.google.com/visionsuccess",
  facebookPage: "https://facebook.com/visionsuccess",
  instagramPage: "https://instagram.com/visionsuccess",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753678062/coach4_nj4xpr.jpg", filename: "coach4_nj4xpr" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Book Cart",
  name: "Book Cart Store",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Dwarka, Delhi",
  contact: "9876523456",
  alternateContact: "9123498765",
  whatsappNumber: "9876523456",
  email: "bookcart@gmail.com",
  website: "https://bookcart.com",
  googleMapLink: "https://maps.google.com/bookcart",
  facebookPage: "https://facebook.com/bookcart",
  instagramPage: "https://instagram.com/bookcart",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753678201/store6_ctui5m.jpg", filename: "store6_ctui5m" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Page Turners Library",
  name: "Page Turners Reading Hub",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Preet Vihar, Delhi",
  contact: "9345678902",
  alternateContact: "9567894321",
  whatsappNumber: "9345678902",
  email: "pageturnerslibrary@gmail.com",
  website: "https://pageturnerslibrary.com",
  googleMapLink: "https://maps.google.com/pageturnerslibrary",
  facebookPage: "https://facebook.com/pageturnerslibrary",
  instagramPage: "https://instagram.com/pageturnerslibrary",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753678254/lib7_lebfo6.jpg", filename: "lib7_lebfo6" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Write Right",
  name: "Write Right Stationery",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Vikaspuri, Delhi",
  contact: "9123498764",
  alternateContact: "9876505678",
  whatsappNumber: "9123498764",
  email: "writeright@gmail.com",
  website: "https://writeright.com",
  googleMapLink: "https://maps.google.com/writeright",
  facebookPage: "https://facebook.com/writeright",
  instagramPage: "https://instagram.com/writeright",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753678330/store3_zeopkx.jpg", filename: "store3_zeopkx" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "iWeb Cafe",
  name: "iWeb Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Indirapuram, Ghaziabad",
  contact: "9876532109",
  alternateContact: "9345678976",
  whatsappNumber: "9876532109",
  email: "iwebcafe@gmail.com",
  website: "https://iwebcafe.com",
  googleMapLink: "https://maps.google.com/iwebcafe",
  facebookPage: "https://facebook.com/iwebcafe",
  instagramPage: "https://instagram.com/iwebcafe",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753678394/cafe3_ntyhid.jpg", filename: "cafe3_ntyhid" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Target Tutorials",
  name: "Target Coaching Centre",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Noida Sector 62",
  contact: "9345674532",
  alternateContact: "9123456743",
  whatsappNumber: "9345674532",
  email: "targettutorials@gmail.com",
  website: "https://targettutorials.com",
  googleMapLink: "https://maps.google.com/targettutorials",
  facebookPage: "https://facebook.com/targettutorials",
  instagramPage: "https://instagram.com/targettutorials",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753678466/coach6_yxgwse.jpg", filename: "coach6_yxgwse" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Book Junction",
  name: "Book Junction Store",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Karol Bagh, Delhi",
  contact: "9876501234",
  alternateContact: "9123498745",
  whatsappNumber: "9876501234",
  email: "bookjunction@gmail.com",
  website: "https://bookjunction.com",
  googleMapLink: "https://maps.google.com/bookjunction",
  facebookPage: "https://facebook.com/bookjunction",
  instagramPage: "https://instagram.com/bookjunction",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753678817/store1_koxcwr.jpg", filename: "store1_koxcwr" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Study Lounge",
  name: "Study Lounge Library",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Vasant Kunj, Delhi",
  contact: "9345612345",
  alternateContact: "9567893210",
  whatsappNumber: "9345612345",
  email: "studylounge@gmail.com",
  website: "https://studylounge.com",
  googleMapLink: "https://maps.google.com/studylounge",
  facebookPage: "https://facebook.com/studylounge",
  instagramPage: "https://instagram.com/studylounge",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753678867/lib2_vgqwdr.jpg", filename: "lib2_vgqwdr" },
  owner: "6870b24612c47ddfa98a0fa5",
  tags: ["wifi available", "group study", "peaceful", "verified"]
},
{
  title: "Paper Palace",
  name: "Paper Palace Stationery",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Punjabi Bagh, Delhi",
  contact: "9123487654",
  alternateContact: "9876502345",
  whatsappNumber: "9123487654",
  email: "paperpalace@gmail.com",
  website: "https://paperpalace.com",
  googleMapLink: "https://maps.google.com/paperpalace",
  facebookPage: "https://facebook.com/paperpalace",
  instagramPage: "https://instagram.com/paperpalace",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753678957/store8_loq3n6.jpg", filename: "store8_loq3n6" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Cyber World",
  name: "Cyber World Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Yamuna Vihar, Delhi",
  contact: "9876598765",
  alternateContact: "9345678909",
  whatsappNumber: "9876598765",
  email: "cyberworldcafe@gmail.com",
  website: "https://cyberworldcafe.com",
  googleMapLink: "https://maps.google.com/cyberworldcafe",
  facebookPage: "https://facebook.com/cyberworldcafe",
  instagramPage: "https://instagram.com/cyberworldcafe",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753678994/cafe1_ucypxu.jpg", filename: "cafe1_ucypxu" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Achievers Academy",
  name: "Achievers Coaching Centre",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Uttam Nagar, Delhi",
  contact: "9345670987",
  alternateContact: "9123456788",
  whatsappNumber: "9345670987",
  email: "achieversacademy@gmail.com",
  website: "https://achieversacademy.com",
  googleMapLink: "https://maps.google.com/achieversacademy",
  facebookPage: "https://facebook.com/achieversacademy",
  instagramPage: "https://instagram.com/achieversacademy",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679028/coach2_bciiou.jpg", filename: "coach2_bciiou" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Page World",
  name: "Page World Bookstore",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Connaught Place, Delhi",
  contact: "9876505678",
  alternateContact: "9123456732",
  whatsappNumber: "9876505678",
  email: "pageworld@gmail.com",
  website: "https://pageworld.com",
  googleMapLink: "https://maps.google.com/pageworld",
  facebookPage: "https://facebook.com/pageworld",
  instagramPage: "https://instagram.com/pageworld",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679138/store9_iriwjm.jpg", filename: "store9_iriwjm" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Smart Reads",
  name: "Smart Reads Library",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Saket, Delhi",
  contact: "9345673210",
  alternateContact: "9567898743",
  whatsappNumber: "9345673210",
  email: "smartreads@gmail.com",
  website: "https://smartreads.com",
  googleMapLink: "https://maps.google.com/smartreads",
  facebookPage: "https://facebook.com/smartreads",
  instagramPage: "https://instagram.com/smartreads",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679177/lib5_ebqe7g.jpg", filename: "lib5_ebqe7g" },
  owner: "6870b24612c47ddfa98a0fa5",
  tags: ["wifi available", "group study", "peaceful", "verified"]
},
{
  title: "The Stationery Hub",
  name: "Stationery Hub",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Ashok Vihar, Delhi",
  contact: "9123456789",
  alternateContact: "9876543211",
  whatsappNumber: "9123456789",
  email: "stationeryhub@gmail.com",
  website: "https://stationeryhub.com",
  googleMapLink: "https://maps.google.com/stationeryhub",
  facebookPage: "https://facebook.com/stationeryhub",
  instagramPage: "https://instagram.com/stationeryhub",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679264/store9_grfcd3.webp", filename: "store9_grfcd3" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Fast Lane Cafe",
  name: "Fast Lane Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Kalkaji, Delhi",
  contact: "9876506789",
  alternateContact: "9345678910",
  whatsappNumber: "9876506789",
  email: "fastlanecafe@gmail.com",
  website: "https://fastlanecafe.com",
  googleMapLink: "https://maps.google.com/fastlanecafe",
  facebookPage: "https://facebook.com/fastlanecafe",
  instagramPage: "https://instagram.com/fastlanecafe",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679311/cafe5_uc2tzf.jpg", filename: "cafe5_uc2tzf" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Champions Institute",
  name: "Champions Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Noida Sector 62",
  contact: "9345676543",
  alternateContact: "9123456781",
  whatsappNumber: "9345676543",
  email: "championsinstitute@gmail.com",
  website: "https://championsinstitute.com",
  googleMapLink: "https://maps.google.com/championsinstitute",
  facebookPage: "https://facebook.com/championsinstitute",
  instagramPage: "https://instagram.com/championsinstitute",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679351/coach3_wtmzvo.webp", filename: "coach3_wtmzvo" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "The Book Shelf",
  name: "The Book Shelf Store",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Model Town, Delhi",
  contact: "9876532109",
  alternateContact: "9123450987",
  whatsappNumber: "9876532109",
  email: "thebookshelf@gmail.com",
  website: "https://thebookshelf.com",
  googleMapLink: "https://maps.google.com/thebookshelf",
  facebookPage: "https://facebook.com/thebookshelf",
  instagramPage: "https://instagram.com/thebookshelf",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679406/book3_ih1feh.jpg", filename: "book3_ih1feh" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Library Hub",
  name: "Library Hub Reading Center",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "GTB Nagar, Delhi",
  contact: "9345677654",
  alternateContact: "9567891234",
  whatsappNumber: "9345677654",
  email: "libraryhub@gmail.com",
  website: "https://libraryhub.com",
  googleMapLink: "https://maps.google.com/libraryhub",
  facebookPage: "https://facebook.com/libraryhub",
  instagramPage: "https://instagram.com/libraryhub",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679452/lib6_s8jywz.jpg", filename: "lib6_s8jywz" },
  owner: "6870b24612c47ddfa98a0fa5",
  tags: ["wifi available", "group study", "peaceful", "verified"]
},
{
  title: "Office Point",
  name: "Office Point Stationery",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Chandni Chowk, Delhi",
  contact: "9123455678",
  alternateContact: "9876501230",
  whatsappNumber: "9123455678",
  email: "officepoint@gmail.com",
  website: "https://officepoint.com",
  googleMapLink: "https://maps.google.com/officepoint",
  facebookPage: "https://facebook.com/officepoint",
  instagramPage: "https://instagram.com/officepoint",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679575/store10_sr0va3.jpg", filename: "store10_sr0va3" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "iConnect Cafe",
  name: "iConnect Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Indirapuram, Ghaziabad",
  contact: "9876509876",
  alternateContact: "9345678900",
  whatsappNumber: "9876509876",
  email: "iconnectcafe@gmail.com",
  website: "https://iconnectcafe.com",
  googleMapLink: "https://maps.google.com/iconnectcafe",
  facebookPage: "https://facebook.com/iconnectcafe",
  instagramPage: "https://instagram.com/iconnectcafe",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679612/cafe6_zijsqj.jpg", filename: "cafe6_zijsqj" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Bright Future Tutorials",
  name: "Bright Future Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Mukherjee Nagar, Delhi",
  contact: "9345673321",
  alternateContact: "9123458888",
  whatsappNumber: "9345673321",
  email: "brightfuturetutorials@gmail.com",
  website: "https://brightfuturetutorials.com",
  googleMapLink: "https://maps.google.com/brightfuturetutorials",
  facebookPage: "https://facebook.com/brightfuturetutorials",
  instagramPage: "https://instagram.com/brightfuturetutorials",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679732/coach7_p7rhma.jpg", filename: "coach7_p7rhma" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Book Corner",
  name: "Book Corner Bookstore",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Paharganj, Delhi",
  contact: "9876504567",
  alternateContact: "9123450999",
  whatsappNumber: "9876504567",
  email: "bookcorner@gmail.com",
  website: "https://bookcorner.com",
  googleMapLink: "https://maps.google.com/bookcorner",
  facebookPage: "https://facebook.com/bookcorner",
  instagramPage: "https://instagram.com/bookcorner",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679784/book5_obu246.jpg", filename: "book5_obu246" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Peace Library",
  name: "Peace Library & Study Hub",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Laxmi Nagar, Delhi",
  contact: "9345672222",
  alternateContact: "9567896543",
  whatsappNumber: "9345672222",
  email: "peacelibrary@gmail.com",
  website: "https://peacelibrary.com",
  googleMapLink: "https://maps.google.com/peacelibrary",
  facebookPage: "https://facebook.com/peacelibrary",
  instagramPage: "https://instagram.com/peacelibrary",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679848/lib10_bgovx1.jpg", filename: "lib10_bgovx1" },
    owner: "6870b24612c47ddfa98a0fa5",
    tags: ["wifi available", "group study", "peaceful", "verified"]
},
{
  title: "Niu Taim Internet",
  name: "Niu Taim Internet Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Noida Sector 15",
  contact: "9876506543",
  alternateContact: "9345677654",
  whatsappNumber: "9876506543",
  email: "clicknetcafe@gmail.com",
  website: "https://clicknetcafe.com",
  googleMapLink: "https://maps.google.com/clicknetcafe",
  facebookPage: "https://facebook.com/clicknetcafe",
  instagramPage: "https://instagram.com/clicknetcafe",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753679907/cafe7_qtz09a.jpg", filename: "cafe7_qtz09a" },
  owner: "6870b24612c47ddfa98a0fa5",
},
{
  title: "Success Gurukul",
  name: "Success Gurukul Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Patel Nagar, Delhi",
  contact: "9345675432",
  alternateContact: "9123456543",
  whatsappNumber: "9345675432",
  email: "successgurukul@gmail.com",
  website: "https://successgurukul.com",
  googleMapLink: "https://maps.google.com/successgurukul",
  facebookPage: "https://facebook.com/successgurukul",
  instagramPage: "https://instagram.com/successgurukul",
  image: { url: "https://res.cloudinary.com/dmhjodkdy/image/upload/v1753680055/coach8_dp88yo.avif", filename: "coach8_dp88yo" },
  owner: "6870b24612c47ddfa98a0fa5",
}

];
 
module.exports = sampleListings ;